version: '3.6'
services:

  nginx:
    image: nginx:1.7.7
    container_name: nginx
    restart: always
    networks:
      - frontend
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - sampledata:/sampledata
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERT:-./ssl/ssl_dev.crt}:/etc/ssl/SSL.crt:ro  # SSL development certificate
      - ${NGINX_SSL_KEY:-./ssl/ssl_dev.key}:/etc/ssl/SSL.key:ro   # SSL development key

  viewer:
    image: ohif/viewer:latest
    container_name: viewer
    depends_on:
#      - mongo
      - orthanc
    restart: always
    networks:
      - frontend
      - backend
#    ports:
#      - 3000:80
#    links:
#      - mongo
#    environment:
#      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/ohif}
    volumes:
      - ${VIEWER_CONFIG:-./config/app-config.js}:/usr/share/nginx/html/app-config.js:ro

#   mongo:
#    image: mongo:4.0.14
#    container_name: mongo
#    networks:
#      - backend
#    ports:
#      - ${MONGO_PORT:-27017}:27017
#    volumes:
#      - ${MONGO_DATA:-./mongo_data}:/data/db

  orthanc:
    image: jodogne/orthanc-plugins:1.5.8
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - sampledata:/sampledata
      - ${ORTHANC_DB:-./orthanc_db}:/var/lib/orthanc/db
      - ${ORTHANC_CONFIG:-./config/orthanc.json}:/etc/orthanc/orthanc.json:ro
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
#    ports:
#      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_DATA_MNT:-/pg_data/data}:${PGDATA:-/var/lib/postgresql/data}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

networks:
  frontend:
  backend:

volumes:
  sampledata:
